// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLhhfR1Glyw2PBMnTBFKtXHgD8ULRPCxs',
    appId: '1:191037013128:web:3bc1c7d043af58dff8333d',
    messagingSenderId: '191037013128',
    projectId: 'assignment-app-8223',
    authDomain: 'assignment-app-8223.firebaseapp.com',
    storageBucket: 'assignment-app-8223.appspot.com',
    measurementId: 'G-E11SFCDYZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGjqlqL_R9UbigodEDIJD2jTJqwjxXUj0',
    appId: '1:191037013128:android:c1f17f83fea862c1f8333d',
    messagingSenderId: '191037013128',
    projectId: 'assignment-app-8223',
    storageBucket: 'assignment-app-8223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSADP9zZlyhgDeVdLFPJYqjL8q_lY0hE',
    appId: '1:191037013128:ios:a6e1bbfc456d8dd1f8333d',
    messagingSenderId: '191037013128',
    projectId: 'assignment-app-8223',
    storageBucket: 'assignment-app-8223.appspot.com',
    iosClientId: '191037013128-eppnprv0j2qscundb607quvas1p4m6h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentApp',
  );
}
